PROC ScrNewEnt
clearwork()
setpos(2,0)
text

    Add new Entity from &mMode.

    This procedure creates the required databases for the new
    entity from the currently selected Entity.
    All new files are empty and will OVERWRITE any existing
    files in the new directory specified below.







    Be careful to keep at least one Entity available, otherwise
    LabMate 2000 will not be able to run.
endtext
return (.t.)

PROC ScrRates
clearwork()
setpos(2,0)
text
    Print a Rates List of all Profiles in the database.

endtext
return (.t.)

PROC ScrProgInf
clearwork()
setpos(2,0)
text
    ABOUT LAB-MATE 2000
    Welcome to Lab-Mate 2000

     Features include:
         Create and Delete Entities
         Create Lab Reports of One or More Test Profiles
         Print & Re-print Individual or Multiple Lab Reports
         Fully customizable Test Profiles Database
         Automatic Storage of Referrals
         Patients Information Database
         Reports - Sales & Analysis Reports, Rates List
         Record Archiving & Retrieval
         Lab Stocks - Stock Control System   (available later version)
         Patient Medical Records System      (available later version)

    Dedicated to Mr. Malick Fernando (NML),
    a sincere friend and life-saver.
endtext
return (.t.)

PROC ScrPatDiag
clearwork()
setpos(2,0)
text
    Patients Medical Records System

endtext
return (.t.)

PROC ScrSAReps
clearwork()
setpos(2,0)
text
    Sales & Analysis Reports

endtext
return (.t.)

PROC ScrStock
clearwork()
setpos(2,0)
text
    Stock Control System

endtext
return (.t.)

PROC ScrPatDB
clearwork()
setpos(2,0)
text
    

endtext
return (.t.)
     
PROC ScrProDB
clearwork()
setpos(2,0)
text
    

endtext
return (.t.)
     
PROC ScrLabReps
clearwork()
setpos(2,0)
text
    Lab Reporting System.

    Create and edit Lab Reports. Profiles can be added and
    removed only prior to payment/printing. Patient
    information can also be retrieved from the Patients
    Database.

    Reports can only be printed after payment has been made.

endtext
return (.t.)

PROC ScrSelComp
clearwork()
setpos(2,0)
text
    Select Default Entity DataBase. (Current Seletion &mMode)

    
endtext
return (.t.)

PROC ScrArchRec
clearwork()
setpos(2,0)
text
    Archival & Retrieval of &mMode files.

endtext
return (.t.)

PROC ScrLogOn
clearwork()
setpos(2,0)
text
    Entity Selection and Information.

endtext
return (.t.)

PROC ScrCompInf
clearwork()
setpos(2,0)
text
    

endtext
return (.t.)

PROC ScrDataFil
clearwork()
setpos(2,0)
text
    View, Edit & Print Data Files.

endtext
return (.t.)

PROC ScrArch
clearwork()
setpos(2,0)
text
    Archival of &mMode files.

endtext
return (.t.)

PROC ScrRetr
clearwork()
setpos(2,0)
text
    Retrieval of &mMode files.

endtext
return (.t.)
