// Program registration information.

#define OWNER           "The Leisure Co."
#define COPYRIGHT       "All rights reserved (1999)"
#define OWNADDRESS      "3/C, Kimbulapitiya Estate, Negombo, Sri Lanka."
#define OWNCONTACT      "Tel: +93 (0)31 22600"

#define PROGRAMNAME    "LAB-MATE 2000"
#define VERSION         "(ver 3.0)"
#define DEVELOPER       "Developed by: Victor and Honorine Wright"

#define REGISTEREDTO   "Negombo Medical Laboratory"
